apiVersion: v1
baseDomain: example.com
metadata:
  name: cloud-lab4

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false 

pullSecret: '<Register in Redhat and generate acess in redhat.io>'


sshKey: 'ssh-ed25519 <public key>'
